name: SOAPUI Tests Workflow V2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
    
jobs:
  soapui-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Run SoapUI Docker Container
      - name: Start SoapUI Container
        run: |
          docker run -d --name soapui \
            -v ${{ github.workspace }}/soapui:/soapui-projects \
            ddavison/soapui
          
      - name: Load test
        run: |
          docker exec soapui /bin/sh -c "
            cd /opt/SoapUI/bin &&
            ./loadtestrunner.sh -sTestSuiteJeroen -cLoadTest -l'LoadTest 1' /soapui-projects/DetermineShippingCosts-soapui-project.xml
          "
      - name: SOAP API test
        run: |
          docker exec soapui /bin/sh -c "
            cd /opt/SoapUI/bin &&
            ./testrunner.sh -sTestSuiteJeroen -cGetPaymentMethodCollection /soapui-projects/DetermineShippingCosts-soapui-project.xml
          "