name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
permissions:
  contents: read
  actions: read
  checks: write
      
jobs:
  Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build & Install
        run: dotnet build
        
        # Playwright tests
      - name: Ensure browsers are installed
        run: | 
          cd PlaywrightTests
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Run GUI test with Playwright
        run: |
          cd PlaywrightTests
          dotnet test --settings:chromium.runsettings
          dotnet test --settings:firefox.runsettings
          dotnet test --settings:webkit.runsettings
          
        # Coverage test
      - name: Install dependencies
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
      - name: run branch coverage tests
        run: |
          cd DetermineShippingCosts.test
          dotnet test --logger trx --collect:"XPlat Code Coverage"
          
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: CodeCoverage
          path: DetermineShippingCosts.test/TestResults/*.trx
          reporter: dotnet-trx
          
      - name: Restore local tools
        run: dotnet tool restore
          
      - name: Generate coverage report
        run: reportgenerator -reports:DetermineShippingCosts.test/TestResults/**/coverage.cobertura.xml -targetdir:./coverage -reporttypes:MarkdownSummary
          
      - name: Create check with coverage report
        uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Code coverage
          conclusion: ${{ job.status }}
          output: '{"summary":"Code coverage"}'
          output_text_description_file: coverage/Summary.md