name: Run Unit and GUI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 # Adjust this based on your project's .NET version
      
      # Install dependencies
      - name: Install dependencies
        run: dotnet restore
        
      
      # Run GUI Tests
      - name: Run GUI Tests
        run: |
          cd PlaywrightTests
          dotnet test
      
      # Upload coverage reports (optional, for debugging)
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
